### ISSUE TITLE
Change TOC appearance for editors to look the same as for external users

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#525] opened 2024-10-09 20:19 UTC
Right now the TOC has two different looks depending on whether a user is logged in to the DM instance or not. It'd be great for the "logged in" look (boxes around folders) to also be the look for non-logged in users, as it looks better.

**Comment by blms** [comment] 2024-10-18 18:20
Closing as duplicate of #415

**Closed by blms** 2024-10-18 18:20 UTC
